#!/bin/bash
set -e
mvn package
spark-submit --class edu.ucr.cs.cs226.gprak001.SparkSqlAsterisxDB --master local[8] target/SparkSqlAsterisxDB-1.0-SNAPSHOT.jar "$1"


curl -v --data-urlencode "statement=DROP dataverse nasalogs if exists;" http://localhost:19002/query/service
curl -v --data-urlencode "statement=CREATE dataverse nasalogs;" http://localhost:19002/query/service
curl -v --data-urlencode "statement=use nasalogs;" http://localhost:19002/query/service

curl -v --data-urlencode "statement=
CREATE TYPE logType AS CLOSED {
  id: uuid,
  host: String,
  logName: String,
  time: bigint,
  method: String,
  URL: String,
  response: bigint,
  bytes: bigint,
  referrer: String?,
  useragent: String?
}" http://localhost:19002/query/service

curl -v --data-urlencode "statement=
CREATE DATASET nasaLogData (logType) PRIMARY KEY id AUTOGENERATED;" http://localhost:19002/query/service

curl -v --data-urlencode "statement=
LOAD DATASET nasaLogData USING
  localfs (('path'='127.0.0.1://$1')
  ,('format'='delimited-text'),('delimiter'='\t'));" http://localhost:19002/query/service

echo "TIME PERIOD between 804571201 and 804571305" >> taskC

echo "Using AsteriskDB before Indexing on time, below is the output for total number of logs within the given time period =======>" >> taskC

curl -v --data-urlencode "statement=
SELECT count(id) FROM nasaLogData WHERE time > 804571201 AND time < 804571305;" http://localhost:19002/query/service >> taskC

curl -v --data-urlencode "statement=DROP INDEX nasaLogData.timeStamp if exists" http://localhost:19002/query/service

curl -v --data-urlencode "statement=CREATE INDEX timeStamp ON nasaLogData(time);" http://localhost:19002/query/service

echo "After Indexing on time, below is the output for total number of logs within the given time period =======>" >> taskC

curl -v --data-urlencode "statement=
SELECT count(id) FROM nasaLogData WHERE time > 804571201 AND time < 804571305;" http://localhost:19002/query/service >> taskC


curl -v --data-urlencode "statement=
SELECT response, sum(bytes)/count(*) FROM nasaLogData GROUP BY response;" http://localhost:19002/query/service >> taskD

curl -v --data-urlencode "statement=
DROP DATASET nasaLogData;" http://localhost:19002/query/service

curl -v --data-urlencode "statement=
DROP TYPE logType;" http://localhost:19002/query/service
